# Site settings
title:          Research
description:    "Hi! I’m Mikołaj, a software engineer intern, student at Warsaw University of Technology, and a passionate musician."
baseurl:        "/"
url:            "https://mikolajszawerda.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Mikołaj Szawerda
  url:          https://research.mszawerd.dev
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# Assets
sass:
  sass_dir:     _sass
  style:        compressed

remote_theme: chesterhow/tale

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
